[project]
name = "otus-mlops-dvc-lesson-dec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.4"
dependencies = [
    "dvc[s3]==3.64.2",
    "loguru==0.7.3",
    "pandas==2.3.3",
    "scikit-learn==1.8.0",
]
